coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flags:
  server:
    carryforward: true
  client:
    carryforward: true