coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flags:
  server:
    carryforward: true
  client:
    carryforward: true

ignore:
  - "/server/models/**/*"
  - "/server/dtos/**/*"
  - "/server/exceptions/**/*"
  - "/server/configurations/security/JwtKeystore.kt"
  - "/server/configurations/security/JwtKeystoreProperties.kt"
