services:
  db:
    image: postgres:latest
    container_name: omnom_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - omnom_data:/var/lib/postgresql/data
    networks:
      - omnom_network

volumes:
  omnom_data:

networks:
  omnom_network:
    driver: bridge