server:
  port: 8081

spring:
  application:
    name: server

  r2dbc:
    url: r2dbc:postgresql://localhost:54321/omnom
    username: omnom
    password: omnom

  datasource:
    url: jdbc:postgresql://localhost:54321/omnom
    username: omnom
    password: omnom
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:54321/omnom
    user: omnom
    password: omnom
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  ai:
    azure:
      openai:
        chat:
          options:
            deployment-name: gpt-4o-mini

keystore:
  location: classpath:/keystore/keystore.p12
  password: ${JWT_KEYSTORE_PASSWORD}
  keyPassword: ${JWT_KEY_PASSWORD}
  alias: jwt
  type: JKS

logging:
  level:
    org:
      springframework:
        security: DEBUG
        test.context: DEBUG
      testcontainers: DEBUG
      flywaydb: DEBUG
