spring:
  application:
    name: server

  datasource:
    url: jdbc:postgresql://localhost:5432/omnom
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    azure:
      openai:
        api-key: ${OPENAI_API_KEY}
        endpoint: https://${OPENAI_RESOURCE}.openai.azure.com/
        chat:
          options:
            deployment-name: gpt-4o-mini