spring:
  application:
    name: server

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/omnom
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/omnom
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  ai:
    azure:
      openai:
        chat:
          options:
            deployment-name: gpt-4o-mini

keystore:
  location: classpath:/keystore/keystore.p12
  password: ${JWT_KEYSTORE_PASSWORD}
  keyPassword: ${JWT_KEY_PASSWORD}
  alias: jwt
  type: JKS

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
