env:
  redirect:
    url: ${REDIRECT_URL}
  datasource:
      database: ${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  openai:
    api-key: ${OPENAI_API_KEY}
    resource: ${OPENAI_RESOURCE}

spring:
  application:
    name: server

  datasource:
    url: jdbc:postgresql://localhost:5432/${env.datasource.database}
    username: ${env.datasource.username}
    password: ${env.datasource.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  ai:
    azure:
      openai:
        api-key: ${env.openai.api-key}
        endpoint: https://${env.openai.resource}.openai.azure.com/
        chat:
          options:
            deployment-name: gpt-4o-mini
