name: Danger

on:
  pull_request:
      branches:
      - main
      types: [opened, edited, synchronize]

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Danger
        uses: danger/danger-js@12.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}