name: build

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
      branches:
        - main
      paths:
        - 'server/**'

jobs:
  server:
    name: Server Module CI Pipeline
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setting up environment
        run: |
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
            echo "OPENAI_RESOURCE=${{ secrets.OPENAI_RESOURCE }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker compose up
        run: docker compose up -d

      - name: Running Ktlint
        run: ./gradlew ktLintCheck

      - name: Run Tests
        run: ./gradlew test

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: server
          name: server-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Building Server Module
        run: ./gradlew build -x test