name: build

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
      branches:
        - main
      paths:
        - 'server/**'
  workflow_dispatch:

jobs:
  server:
    name: Server Module CI Pipeline
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_RESOURCE: ${{ secrets.OPENAI_RESOURCE }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      JWT_KEYSTORE_PASSWORD: ${{ secrets.JWT_KEYSTORE_PASSWORD }}
      JWT_KEY_PASSWORD: ${{ secrets.JWT_KEY_PASSWORD }}
      OAUTH2_GITHUB_CLIENT_ID: ${{ secrets.OAUTH2_GITHUB_CLIENT_ID }}
      OAUTH2_GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH2_GITHUB_CLIENT_SECRET }}
      OAUTH2_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
      OAUTH2_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Running Ktlint
        run: ./gradlew ktLintCheck

      - name: Run Tests
        run: ./gradlew test

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: server
          name: server-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Building Server Module
        run: ./gradlew build -x test